### ISSUE TITLE
Application crashes when there is no connection available

### ISSUE THREAD

**Issue by Nahrawene-ben-hmida** [ScreebApp/flutter-screeb-plugin#10]
Here is the trace logs : (just make sure that the app is offline):

`E/Screeb  (11955): TargetingCheckApi Network error : Unable to resolve host "rpc.screeb.app": No address associated with hostname java.net.UnknownHostException: Unable to resolve host "rpc.screeb.app": No address associated with hostname null
E/Screeb  (11955): Command cmd Targeting.RefreshTargetCheck java.net.UnknownHostException: Unable to resolve host "rpc.screeb.app": No address associated with hostname null
E/Screeb  (11955): TargetingCheckApi Network error : Unable to resolve host "rpc.screeb.app": No address associated with hostname java.net.UnknownHostException: Unable to resolve host "rpc.screeb.app": No address associated with hostname null
E/Screeb  (11955): Command cmd Targeting.RefreshTargetCheck java.net.UnknownHostException: Unable to resolve host "rpc.screeb.app": No address associated with hostname null
I/pensya.revampe(11955): Background concurrent copying GC freed 149290(7639KB) AllocSpace objects, 18(1232KB) LOS objects, 49% free, 9972KB/19MB, paused 698us total 182.133ms
E/AndroidRuntime(11955): FATAL EXCEPTION: DefaultDispatcher-worker-4`

**Comment by samber** [comment]
Hi @Nahrawene-ben-hmida 

What version of the SDK are you using?

Our targeting engine needs a connection to internet in order to run some checks. It is not supposed to crash for disconnected users

**Comment by Nahrawene-ben-hmida** [comment]
Hello @samber, 
for the Flutter SDK : 3.7.5
Screeb : 0.2.5
At least should handle the case when there is no connection to make sure that the app doesn't crash (hostname null)
`No address associated with hostname java.net.UnknownHostException: Unable to resolve host "rpc.screeb.app": No address associated with hostname null `

**Comment by cley44** [comment]
Hello @Nahrawene-ben-hmida

We released version 0.2.6 yesterday, that should fix the crash

**Comment by Nahrawene-ben-hmida** [comment]
Thanks
