### ISSUE TITLE
Error when trying to change identity on Android.

### ISSUE THREAD

**Issue by santiagocarod** [ScreebApp/flutter-screeb-plugin#12]
Hi,

I'm having this issue

Steps to reproduce:

1. Init Sdk with null user id
  *  ```PluginScreeb.initSdk(<screebAndroidChannel>,<screebIOSChannel>,null);```
 2. Set Identity
  *  ```PluginScreeb.setIdentity(<userId#1>);```
  * Note : Until here everything is working good and the ```PluginScreeb.debugTargeting()``` is working as expected
  3. [Reset Identity (User logs out)](https://developers.screeb.app/sdk-flutter/identity)
  *  ```PluginScreeb.resetIdentity();```
  4. Set new Identity (Another user logs in in without closing the app)
  *  ```PluginScreeb.setIdentity(<userId#2>);```
  * Here the plugins seems to break and the ```PluginScreeb.debugTargeting()``` is not displaying anything and the survey is not being displayed where it should. 

Note: This only happens with the Android build. The iOS build with the same code works well and it displays the surveys in both users and saves their responses in their corresponding user id's. 

Info:
```
  Flutter Sdk: 3.16.9
  plugin_screeb: 2.0.20
```

**Comment by Alexays** [comment]
Hi, we just released a new version `2.0.21`, can you try it?

**Comment by santiagocarod** [comment]
Im sorry for the delay, i'm not used to check Github and forgot about this.

Yes I can confirm that in this version is working for me.

Thanks 😃
