### ISSUE TITLE
Issue with track screen

### ISSUE THREAD

**Issue by tripleP16** [ScreebApp/flutter-screeb-plugin#13]
Hi, 
I'm facing a weird issue when I try to track a screen, it seems  the screen it's being tracked as an event , in the dashboard the screens are being showed as events and not as screens.

Steps to reproduce: 
1. Init the sdk
2. Use track screen method  PluginScreeb.trackScreen(screenName);

Versions: 
Flutter : 3.16.9
plugin_screeb: 2.0.21

**Comment by samber** [comment]
Hi Pablo,

Can you open a ticket in the support, please?

![image](https://github.com/ScreebApp/flutter-screeb-plugin/assets/2951285/86d13ffe-fde7-4e21-b21a-0810a9544757)

We need more information about your account (email, workspace name, screen name...)

**Comment by tripleP16** [comment]
okok
